accounts:
  - 'thebrettway'
  - '_AndresSalinas_'
  - 'champtgram'
  - 'KosherPlug'
  - 'Archemist23NFT'
  - 'BattleguruNFT'
  - 'cbassg16'
  - 'ryandcrypto'
  - 'BentoBoiNFT'
  - 'NFTLlama'
  - 'OttoSuwenNFT'
  - 'TheShamdoo'
  - 'Zeneca_33'
  - 'squidNFT'
  - 'ZssBecker'
  - 'elliotrades'
  - 'JRNYcrypto'
  - 'PopeyesNFTs'
  - 'JamesCiesluk'
  - 'feyi_x'
  - 'Ladimeji3'
  - 'thegreatola'
  - 'ruledout_'