accounts:
  - 'thebrettway'
  - '_AndresSalinas_'
  - 'champtgram'
  - 'KosherPlug'
  - 'Archemist23NFT'
  - 'BattleguruNFT'
  - 'cbassg16'
  - 'ryandcrypto'
  - 'BentoBoiNFT'
  - 'NFTLlama'
  - 'OttoSuwenNFT'
  - 'TheShamdoo'
  - 'Zeneca_33'
  - 'squidNFT'
  - 'ZssBecker'
  - 'elliotrades'
  - 'JRNYcrypto'
  - 'PopeyesNFTs'
  - 'JamesCiesluk'
  - 'feyi_x'
  - 'Ladimeji3'
  - 'thegreatola'
  - 'ruledout_'

words:
  - Free Mint
  - Private Discord
  - Discord invite only
  - Coming soon
  - DM for collaboration
  - DM for
  - Discord closed
  - No discord
  - No Roadmap
  - Mint date
  - Founded by
  - Created by
  - Minting
  - 'Discord: https?:\/\/t.co\/\S+'
  - 'Discord:'
  - 'Mint:'
