accounts:
  - 'thebrettway'
  - '_AndresSalinas_'
  - 'champtgram'
  - 'KosherPlug'
  - 'Archemist23NFT'
  - 'BattleguruNFT'
  - 'cbassg16'
  - 'ryandcrypto'
  - 'BentoBoiNFT'
  - 'NFTLlama'
  - 'OttoSuwenNFT'
  - 'TheShamdoo'
  - 'Zeneca_33'
  - 'squidNFT'
  - 'ZssBecker'
  - 'elliotrades'
  - 'JRNYcrypto'
  - 'PopeyesNFTs'
  - 'JamesCiesluk'
  - 'feyi_x'
  - 'Ladimeji3'
  - 'thegreatola'
  - 'ruledout_'

words:
  - (Free|free) (Mint|mint)
  - (Private|private) (Discord|discord)
  - (Discord|discord) (Invite|invite) (Only|only)
  - (Coming|coming) (soon|Soon)
  - (DM|dm|Dm) (for|For) (collaboration|Collaboration)
  - (DM|dm|Dm) (for|For)
  - (Discord|discord) closed
  - (No|no) (Discord|discord)
  - (No|no) (Roadmap|roadmap)
  - (Mint|mint) (date|Date)
  - (Founded|founded) (by|By)
  - (Created|created) (by|By)
  - (Minting|minting)
  - '(Discord|discord): https?:\/\/t.co\/\S+'
  - '(Discord|discord):'
  - 'Mint:'
  - '(Supply|supply)'
